export type Evidence = 'VERIFIED' | 'PARTIAL' | 'STALE' | 'CONFLICTING' | 'UNKNOWN';
export type State =
  'READY_TO_APPLY' | 'WITHIN_REACH' | 'CONDITIONAL_PATH' | 'BLOCKED' | 'INDETERMINATE';
export type Verdict = 'PASS' | 'FAIL' | 'UNKNOWN' | 'NOT_APPLICABLE';
export type CostState = 'WITHIN_BUDGET' | 'OVER_BUDGET' | 'UNKNOWN';
export type Timeline = 'FEASIBLE' | 'TIGHT' | 'MISSED' | 'UNKNOWN';
export type Fact = {
  id: string;
  field: string;
  value: unknown;
  statement: string;
  source_url: string | null;
  page_title: string | null;
  retrieved_at: string;
  intake: string;
  scope: Record<string, string>;
  evidence: Evidence;
  provenance: 'OFFICIAL_FACT' | 'UNKNOWN' | 'PRODUCT_ASSUMPTION' | 'PATHSHIFT_INFERENCE';
  notes: string;
};
export type Rule = {
  id: string;
  label: string;
  op: 'ATOM' | 'ALL' | 'ANY_OF' | 'EXEMPTION' | 'CONDITIONAL_PATH' | 'POST_ENROLMENT';
  strength: 'HARD' | 'SOFT' | 'INFO';
  facts: string[];
  field?: string;
  comparator?: 'EQ' | 'NEQ' | 'GTE' | 'LTE' | 'PRESENT' | 'IN' | 'BEFORE' | 'AFTER' | 'SATISFIES';
  value?: unknown;
  valueKey?: string;
  unknown?: boolean;
  children?: Rule[];
  requirement?: Rule;
  exemption?: Rule;
  direct?: Rule;
  alternative?: Rule;
  action?: string;
  immutable?: boolean;
};
export type Deadline = {
  type: string;
  plan: string;
  date: string;
  time: string | null;
  timezone: string | null;
  fact: string;
};
export type Program = {
  id: string;
  name: string;
  short: string;
  degree: string;
  country: string;
  city: string;
  initials: string;
  color: string;
  structure: string;
  tags: string[];
  rules: Rule[];
  deadlines: Deadline[];
  cost?: {
    min: number;
    max: number;
    currency: 'USD' | 'CAD' | 'GBP';
    year: string;
    complete: boolean;
    fact: string;
  };
  conditional?: { name: string; fact: string; note: string };
};
export type Profile = {
  personal_plan?: {
    id: string;
    title: string;
    kind: 'STUDY' | 'ACTIVITY';
    due: string | null;
    notes: string;
    complete: boolean;
  }[];
  name: string;
  age: number;
  citizenship: string;
  applicant_type: string;
  intake: string;
  major: string;
  countries: string[];
  country_locks: string[];
  geography_flexible: boolean;
  financial_flexibility: boolean;
  budget_hard: boolean;
  curriculum: string;
  raw_grade: string;
  raw_scale: string;
  ib_total: number | null;
  math_aa_hl: number | null;
  english_a: boolean | null;
  ib_diploma: boolean | null;
  ib_courses: number | null;
  hl_courses: number | null;
  academics_completed: boolean;
  senior_english: boolean | null;
  aif: boolean;
  documents_ready: boolean;
  documents_by_program?: Record<string, boolean>;
  ielts: {
    status: string;
    overall: number | null;
    reading: number | null;
    writing: number | null;
    listening: number | null;
    speaking: number | null;
    date: string | null;
  };
  sat: { status: string; score: number | null; date: string | null };
  act: { status: string; score: number | null; date: string | null };
  det: number | null;
  toefl: {
    score: number | null;
    writing: number | null;
    speaking: number | null;
    date: string | null;
  };
  budgets: { USD: number | null; CAD: number | null; GBP: number | null };
  interest: string;
  expected_score_date: string | null;
  shortlist: string[];
  completed: string[];
};
export type RuleResult = {
  id: string;
  label: string;
  result: Verdict;
  strength: Rule['strength'];
  facts: string[];
  reason: string;
  field?: string;
  action?: string;
  immutable?: boolean;
  children: RuleResult[];
  conditional?: boolean;
};
export type Recourse = {
  actions: string[];
  mutation: Partial<Profile>;
  feasibility: Timeline;
  improved_rules: string[];
  unlocks: boolean;
  note: string;
};
export type Result = {
  program: Program;
  admission_state: State;
  evidence_state: Evidence;
  timeline_state: Timeline;
  cost_state: CostState;
  reference_cost_state: CostState;
  rules: RuleResult[];
  blockers: RuleResult[];
  unknowns: RuleResult[];
  passed: number;
  total: number;
  recourse: Recourse[];
  in_scope: boolean;
  deadline: Deadline | null;
};
export type Task = {
  id: string;
  title: string;
  description: string;
  type: 'SCORE' | 'DOCUMENT' | 'VERIFY' | 'BUDGET';
  programs: string[];
  facts: string[];
  deadline: string | null;
  dependencies: string[];
  complete: boolean;
  requires_value: boolean;
  impact: number;
};
export type Evaluation = {
  profile: Profile;
  programs: Result[];
  roadmap: Task[];
  next_action: Task | null;
  diagnosis: { strengths: string[]; constraints: string[]; gaps: string[] };
  evaluated_at: string;
  dataset_version: string;
};
export type Diff = {
  changed_states: { id: string; before: State; after: State }[];
  changed_rules: {
    program: string;
    rule: string;
    label: string;
    before: Verdict;
    after: Verdict;
  }[];
  removed_blockers: string[];
  added_blockers: string[];
  changed_costs: { id: string; before: CostState; after: CostState }[];
  changed_timelines: string[];
  tasks_added: string[];
  tasks_removed: string[];
  next_before: string | null;
  next_after: string | null;
};
export type Simulation = { before: Evaluation; after: Evaluation; diff: Diff };
